<h1>About uS </h1>
    <p>Welcome to <strong>BacolodCityPoliceOffice.org</strong>, a free online website galery for webmasters. We afford a variety of free downloads, such as <strong><a href="http://www.freecsstemplate.net">Free Css Templates</a></strong>,  Free Flash Templates, Free Web Templates and Free Website Templates. We  also offer to you free custom design and redesign of your site! Yes,  it's realy try. Today you can <strong>download free website templates</strong>;)  Please choose website design templates and download to your laptop.  After this just change content and images and you will get your own Web  Site.<br />
    All our <strong><a href="http://www.freecsstemplate.net" title="Css Templates">Css Templates</a></strong> are free for any type of personal or commercial use (provided you  follow the license). You don't have to pay money for us! All we ask is  that you link back to our website in some way. Our team try update  templates database every day. So you can check our templates every day.  ENJOY! </p>
              <p>This website template is repeased under a Creative Commons Attribution 2.5 License</p>
		<p>We request you retain the full copyright notice below including the link to our site. This not only gives respect to the large amount of time given freely by the developers but also helps build interest, traffic and use of our free and paid designs. If you cannot (for good reason) retain the full copyright we request you at least leave in place the Website Templates line, with Website Templates linked to www.freecsstemplate.net. If you refuse to include even this then support may be affected.</p>
    <p class="date"><img src="<?php echo WEB_ROOT;?>admin/include/images/comment.gif" alt="" /> <a href="#">Comments(2)</a> <img src="<?php echo WEB_ROOT;?>admin/include/images/timeicon.gif" alt="" /> 21.02.</p>
    <h2>Bacolod City Profile </h2>
    <p><br />
      Bacolod City is located on the northwestern coast of the Province of  Negros Occidental. It is bounded on the northwest by the town of  Talisay; on the east by the City of Silay; on the east and southwest by  the town of Murcia; on the southwest by the City of Bago; and in the  west by the Guimaras Strait. The global location of Bacolod City is 10  degrees, 40 minutes 40 seconds - north and 122 degrees 54 minutes 25  seconds - east with Bacolod Public Plaza as the benchmark.<br /><br />
      <strong>Bacolod City</strong> is the capital and largest highly urbanized mid-size <a href="http://en.wikipedia.org/wiki/Philippine" title="Philippine">Philippine</a> <a href="http://en.wikipedia.org/wiki/Philippine_city" title="Philippine city">City</a> of the <a href="http://en.wikipedia.org/wiki/Philippine_province" title="Philippine province">province</a> of <a href="http://en.wikipedia.org/wiki/Negros_Occidental_province" title="Negros Occidental province">Negros Occidental</a>. Having a total of 499,497 inhabitants as of August 1, 2007, it is the most populous city in the <a href="http://en.wikipedia.org/wiki/Western_Visayas" title="Western Visayas">Western Visayas Region</a><a href="http://en.wikipedia.org/wiki/Bacolod_City#cite_note-1">.</a> It is notable for its <a href="http://en.wikipedia.org/wiki/MassKara_Festival" title="MassKara Festival">MassKara Festival</a> held during October. Known for being a relatively friendly city, it  bears the nickname &quot;City of Smiles&quot; and the &quot;Football City of the  Philippines&quot;. Bacolod City recently topped a survey by <em>MoneySense Magazine</em> as the &quot;Best Place to Live in the Philippines&quot;.<a href="http://en.wikipedia.org/wiki/Bacolod_City#cite_note-2"></a><br />
    </p>
    <p class="date"><img src="<?php echo WEB_ROOT;?>admin/include/images/comment.gif" alt="" /> <a href="#">Comments(2)</a> <img src="images/timeicon.gif" alt="" /> 21.02.</p>
    <h2>What does Css Template mean?</h2>
    <p>Css Template is a ready-made XHTML Site that you can download and use for absolute free! <strong>Css Template</strong> was created by independent designers from Ukraine. You need only to  make your adjustments and your css site is ready. If you open html file  you can easily change the text information and graphics of the site.  There’s no need to make design - our designers already did it. After  your text and graphics adjustments you need only to upload files (html,  css, images) to your server and enjoy your ready Css Site! Using <strong><a href="http://www.freecsstemplate.net" title="free css templates">Free Css Templates</a></strong> you can save your time and money!</p>
    <p class="date"><img src="<?php echo WEB_ROOT;?>admin/include/images/comment.gif" alt="" /> <a href="#">Comments(2)</a> <img src="<?php echo WEB_ROOT;?>admin/include/images/timeicon.gif" alt="" /> 21.02.</p>